model = "gpt-5.5"
model_reasoning_effort = "medium"
approvals_reviewer = "user"

[plugins."github@openai-curated"]
enabled = true

[plugins."hugging-face@openai-curated"]
enabled = true

[plugins."build-macos-apps@openai-curated"]
enabled = true

[plugins."build-web-apps@openai-curated"]
enabled = true

[plugins."life-science-research@openai-curated"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[features]
prevent_idle_sleep = true
memories = true

[memories]
generate_memories = true
use_memories = true
